apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: test-gogo-az-16 
  janus-idp.io/tekton: test-gogo-az-16
  backstage.io/kubernetes-id: test-gogo-az-16
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: test-gogo-az-16
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml